site_name: Arterial BP Triggering

site_description: 

repo_url: https://github.com/JoshBradshaw/Arterial-BP-MRI-Triggering-Unit

pages:
- ['index.md', 'System Overview']
- ['instructions/user_manual.md', 'Instructions', 'User Manual']
- ['instructions/guidelines-for-adapting-to-new-instrument.md', 'Instructions', 'Guidelines for using a Different Pressure Measurement System']
- ['instructions/reflash-the-microcontroller.md', 'Instructions', 'Reflashing the Microcontroller']
- ['system_design/apb-triggering.md', 'System Design', 'System Block Diagram']
- ['system_design/apb-triggering.md', 'System Design', 'Triggering Algorithm']
- ['system_design/adaptive-gain-adjustment.md', 'System Design', 'Variable Gain Amplifier']
- ['system_design/gui-design.md', 'System Design', 'Monitoring Tool']
- ['system_design/pcb-design.md', 'System Design', 'PCB']
- ['system_design/testing-australian-data.md', 'System Design', 'Validation']

theme: readthedocs
copyright: Copyright &copy; 2015, <a href="http://joshbradshaw.github.io/">Josh Bradshaw</a>.
google_analytics: 