site_name: Arterial BP Triggering

site_description: 

repo_url: https://github.com/JoshBradshaw/Arterial-BP-MRI-Triggering-Unit

pages:
- ['index.md', 'System Overview']
- ['build_log/apb-triggering.md', 'Build Log', 'Triggering Algorithm']
- ['build_log/set-adaptive-gain-algorithm.md', 'Build Log', 'Gain Adjustment Algorithm']
- ['build_log/adaptive-gain-adjustment.md', 'Build Log', 'Variable Gain Amplifier']
- ['build_log/gui-design.md', 'Build Log', 'Monitoring Tool']
- ['build_log/pcb-design.md', 'Build Log', 'PCB']
- ['build_log/testing-australian-data.md', 'Build Log', 'Validation']
- ['instructions/user_manual.md', 'Instructions', 'User Manual']
- ['instructions/guidelines-for-adapting-to-new-instrument.md', 'Instructions', 'Guidelines for using a Different Pressure Measurement System']


copyright: Copyright &copy; 2015, <a href="https://twitter.com/_tomchristie">Josh Bradshaw</a>.
google_analytics: 